### ISSUE TITLE
portability

### ISSUE THREAD

**Issue by jddurand** [CObjectSystem/COS#10]
A wish, not really an issue - I am very tempted to use COS but find port part tedious - what about aleviating this by using cmake to generate makefile and configuration files, and to use tinycthreads for the threads capability ?

**Comment by jddurand** [comment]
addendum: I saw other similar issues - if you don't mind I forked and will work on that

**Comment by devel-chm** [comment]
cmake configuration and compilation would be nice.  I'm interested in using COS for some projects for which I need support for non-unix platforms (i.e., MS windows).

I did a quick look at the tinycthreads project.  It doesn't look as though it supports thread local storage for MacOS X systems yet.

**Comment by devel-chm** [comment]
Regarding portability, I would like use COS as part of a perl application.  Consequently, I'm re-implementing the COS tools cosgen, cosprp, cossym, and coscmt in perl.

**Comment by eritain** [comment]
> COS as part of a perl application

Could you say more about this? I'm a Perl hacker myself and I'm intrigued by the possibilities of tying in a fast object system.

**Comment by devel-chm** [comment]
The specific application is a next generation implementation of PDL (the Perl Data Language).  The current PDL uses custom C API and XS code generation in the implementation.  As a result, it is tied in tightly with the specifics of perl.  My idea, was to use the COS to provide the support for data types, computation, and other OO operations at the C level---ideally it would by symmetric with a new Perl OO layer as a Moo[se] class.  The nice thing is since COS is a C library, there is a C FFI that can be wrapped by almost every language out there that supports the C FFI, including Perl6.

**Comment by devel-chm** [comment]
I've gotten perl implementations of cosgen, cosprp, and cossym in the cos_perl_bin branch of my fork of the COS repo at https://github.com/devel-chm/COS/tree/cos_perl_bin

I think the cosgen.pm and cosprp.pm give the same results as the original shell/unix utils version.

The cossym.pm is implemented but it is complicated enough that I have not been able to verify its operation if only because it has a lot more options to check...

**Comment by devel-chm** [comment]
I'm able to replace the original shell scripts for cosgen, cosprp, and cossym by the perl implementations and everything builds and runs as much as it does with the originals.  The perl based versions are considerably faster but my goal was to be able to support windows which doesn't have a useful shell/posix environment.

**Comment by ldeniau** [comment]
same as #7
