### ISSUE TITLE
auto objects and cos_init()

### ISSUE THREAD

**Issue by bkerin** [CObjectSystem/COS#21]
It took me some time to realize why this program seg faults:  

  OBJ anint = aInt(42);
  fprintf (stderr, "int: %i\n", gint(anint));

This one is annoying because of it gets masked by other code which does cos_init().  Always doing an explicit cos_init() is the safe thing but the OOPSLA paper doesn't mention this and the examples don't show it.  This 

It seems to me that in debug mode (or something) the gint() (and the like) might be able to trigger a
check of cos_symbol.c/init_done static (through an interface function).  Or maybe that
would be regarded as too slow even for debug mode, I don't know.

This code does give a nice explanation:

  OBJ anint = aInt(42);
  cos_init();
  fprintf (stderr, "int: %i\n", gint(anint));

COS says:

  COS-Abort[8876]: invalid class id 671088640 - dynamic object already destroyed or automatic object used *before* COS initialization

I'm really just going through and documenting all the trip-ups I make as I get started
with COS.

**Comment by ldeniau** [comment]
Hi,

On 10 Dec 2018, at 01:36, bkerin <notifications@github.com<mailto:notifications@github.com>> wrote:


It took me some time to realize why this program seg faults:

OBJ anint = aInt(42);
fprintf (stderr, "int: %i\n", gint(anint));

This one is annoying because of it gets masked by other code which does cos_init(). Always doing an explicit cos_init() is the safe thing but the OOPSLA paper doesn't mention this and the examples don't show it. This

I am pretty sure that I wrote somewhere that COS must be initialised before using automatic objects, which is automatic on first message sent. aInt is not a message but an automatic object constructor, i.e. a macro, and therefore does not initialise COS.

In normal application, you always start the main by allocating an AutoRelease pool, which is enough to init COS.

It seems to me that in debug mode (or something) the gint() (and the like) might be able to trigger a
check of cos_symbol.c/init_done static (through an interface function). Or maybe that
would be regarded as too slow even for debug mode, I don't know.

This code does give a nice explanation:

OBJ anint = aInt(42);
cos_init();
fprintf (stderr, "int: %i\n", gint(anint));

COS says:

COS-Abort[8876]: invalid class id 671088640 - dynamic object already destroyed or automatic object used before COS initialization

I'm really just going through and documenting all the trip-ups I make as I get started
with COS.

Nice. If I have some time, I should write some wki now that COS is on GitHub…

It’s true true that when I was using COS every day, I was never making this kind of mistake, but now I forgot these points…

Best,
Laurent.

--
Laurent Deniau                           http://cern.ch/mad
Accelerators Beam Physics        mad@cern.ch<mailto:mad@cern.ch>
CERN, CH-1211 Geneva 23       Tel: +41 (0) 22 767 4647

**Comment by ldeniau** [comment]
In principle, one shouldn't start with an automatic object, the only case where this could happen. The best is always beginning with an AutoRelease pool, and its creation will automatically initialize COS as it sends a message.
