### ISSUE TITLE
Support Pelles C

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [CObjectSystem/COS#44]
http://www.smorgasbordet.com/pellesc/

**Comment by ghost** [comment]
This is impossible because COS needs a POSIX shell to work. This issue could be closed as not planned @ldeniau

**Comment by ldeniau** [comment]
I don't use these platforms, propose PR to solve your issue.

**Comment by 3313005304** [comment]
99596




爱雪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CObjectSystem/COS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月21日(星期五) 中午1:33
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [CObjectSystem/COS] Support Pelles C (Issue #44)





 
This is impossible because COS needs a POSIX shell to work. This issue could be closed as not planned @ldeniau

**Comment by 3313005304** [comment]
456




爱雪
***@***.***



&nbsp;
